<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifiers>osx-arm64;win-x64;linux-x64</RuntimeIdentifiers>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DeltaXaml.Samples.Snake</RootNamespace>
    <AssemblyName>DeltaXAML.Samples.Snake</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Delta.Diagnostics.Contract" Version="*" />
    <PackageReference Include="DeltaMaths" Version="0.0.10.6046" />
    <PackageReference Include="DeltaText" Version="0.0.7.6914" />
    <PackageReference Include="DeltaRender" Version="*" />
    <PackageReference Include="DeltaRender.Platform.SDL3" Version="*" />
    <PackageReference Include="DeltaRender.Vulkan" Version="*" />
    <ProjectReference Include="../../../DeltaRender/src/DeltaRender.Text/DeltaRender.Text.csproj" />
    <ProjectReference Include="../../../DeltaRender/src/DeltaRender.XAML/DeltaRender.XAML.csproj" />
    <ProjectReference Include="../../../DeltaShader/src/DeltaShader.UI/DeltaShader.UI.csproj">
      <AdditionalProperties>DeltaShaderPublishPath=$(TargetDir)DeltaShader\DeltaShader.UI\</AdditionalProperties>
    </ProjectReference>
    <ProjectReference Include="../../../DeltaShader/src/DeltaShader.Text/DeltaShader.Text.csproj">
      <AdditionalProperties>DeltaShaderPublishPath=$(TargetDir)DeltaShader\DeltaShader.Text\</AdditionalProperties>
    </ProjectReference>
    <PackageReference Include="SDL3-CS" Version="*" />
    <PackageReference Include="Silk.NET.MoltenVK.Native" Version="*" GeneratePathProperty="true" />
    <ProjectReference Include="../../src/DeltaXAML/DeltaXAML.csproj" />
    <ProjectReference Include="../../src/DeltaXAML.Contract/DeltaXAML.Contract.csproj" />
    <ProjectReference Include="../../src/DeltaXAML.Generator/DeltaXAML.Generator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <Analyzer Include="../../src/DeltaXAML.Generator/bin/Release/net8.0/DeltaXAML.Compiler.dll" />
    <Analyzer Include="../../src/DeltaXAML.Generator/bin/Release/net8.0/DeltaXAML.Contract.dll" />
    <Analyzer Include="../../src/DeltaXAML.Generator/bin/Release/net8.0/DeltaXAML.dll" />
    <Analyzer Include="../../src/DeltaXAML.Generator/bin/Release/net8.0/Delta.Diagnostics.Contract.dll" />
    <Analyzer Include="../../src/DeltaXAML.Generator/bin/Release/net8.0/DeltaMaths.dll" />
  </ItemGroup>

  <ItemGroup>
    <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="DeltaXamlClassName" />
    <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="DeltaXamlNamespace" />
    <AdditionalFiles Include="MainWindow.dxaml"
                     DeltaXamlClassName="SnakeArtifact"
                     DeltaXamlNamespace="DeltaXaml.Samples.Snake.Generated" />
    <None Update="MainWindow.dxaml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Assets/LuckiestGuy-Regular.ttf"
          Link="Assets/LuckiestGuy-Regular.ttf"
          CopyToOutputDirectory="PreserveNewest" />
    <Content Include="$(PkgSilk_NET_MoltenVK_Native)/runtimes/osx/native/libMoltenVK.dylib"
             Condition=" '$(RuntimeIdentifier)' == 'osx-arm64' Or '$(RuntimeIdentifier)' == 'osx-x64' ">
      <Link>libMoltenVK.dylib</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="$(PkgSilk_NET_MoltenVK_Native)/runtimes/osx/native/MoltenVK_icd.json"
             Condition=" '$(RuntimeIdentifier)' == 'osx-arm64' Or '$(RuntimeIdentifier)' == 'osx-x64' ">
      <Link>MoltenVK_icd.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
