<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Delta.XAML.Contract</AssemblyName>
    <RootNamespace>Delta.XAML.Contract</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../Maths/Delta.Maths.csproj" />
    <ProjectReference Include="../../../DeltaText/Delta.Text.csproj" />
  </ItemGroup>
</Project>
