<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DeltaXAML.TraceReport</RootNamespace>
    <AssemblyName>DeltaXAML.TraceReport</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DeltaMaths" Version="*" />
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.0.2" />
  </ItemGroup>
</Project>
