<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><RootNamespace>DeltaXAML.Core</RootNamespace><AssemblyName>DeltaXAML.Core</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="../DeltaXAML.Abstractions/DeltaXAML.Abstractions.csproj" /><ProjectReference Include="../Delta.XAML.Contract/Delta.XAML.Contract.csproj" /><ProjectReference Include="../../../DeltaDiagnostics/src/Delta.Diagnostics.Contract/Delta.Diagnostics.Contract.csproj" /><ProjectReference Include="../../../Maths/Delta.Maths.csproj" /><ProjectReference Include="../../../DeltaText/Delta.Text.csproj" /></ItemGroup></Project>
