<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DeltaXAML.Contract</AssemblyName>
    <RootNamespace>Delta.XAML.Contract</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../DeltaMaths/src/DeltaMaths/DeltaMaths.csproj" />
    <ProjectReference Include="../../../DeltaText/src/DeltaText/DeltaText.csproj" />
  </ItemGroup>
</Project>
