<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DeltaXaml.Samples.RoundedRectangle.Headless</RootNamespace>
    <AssemblyName>DeltaXAML.Samples.RoundedRectangle.Headless</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DeltaXAML" Version="*" />
    <PackageReference Include="DeltaText" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="RoundedRectangles.dxaml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
