using System.Runtime.InteropServices; using DeltaXAML.Abstractions; using DeltaXAML.Core;
static class Assert { public static void True(bool v,string m){if(!v)throw new Exception(m);} public static void Equal<T>(T x,T y,string m){if(!EqualityComparer<T>.Default.Equals(x,y))throw new Exception(m);} }
internal static class Program
{
    public static void Main()
    {
        var loaded=XamlLoader.Load("<StackPanel Orientation=\"Horizontal\" Width=\"320\" Height=\"180\"><Panel Width=\"40\" Height=\"20\" Background=\"#FF0000\" /><Panel Fill=\"true\" Background=\"#00FF00\" /></StackPanel>");
        Assert.True(loaded.Success,"valid StackPanel XAML"); Assert.Equal(2,loaded.Root!.Children.Count,"child count"); var frame=new UiFrame(loaded.Root); frame.Layout(new(320,180),1); Assert.Equal(new UiRect(0,0,40,180),loaded.Root.Children[0].Bounds,"first child bounds"); Assert.Equal(new UiRect(40,0,280,180),loaded.Root.Children[1].Bounds,"fill child bounds"); var draw=frame.ExtractDrawList(new UiFrameContext(new(320,180),1,1)); Assert.Equal(2,draw.Commands.Length,"rectangle count"); Assert.Equal(UiDrawKind.Rectangle,draw.Commands.Span[0].Kind,"draw kind"); Assert.True(draw.Clips.Length>=3,"clip entries");
        var commandMemory=draw.Commands; var clipMemory=draw.Clips; Assert.True(MemoryMarshal.TryGetArray(commandMemory,out ArraySegment<UiDrawCommand> commandStorage),"command backing storage"); Assert.True(MemoryMarshal.TryGetArray(draw.Commands,out ArraySegment<UiDrawCommand> commandStorageAgain),"command backing storage again"); Assert.True(ReferenceEquals(commandStorage.Array,commandStorageAgain.Array),"commands reuse backing array"); Assert.True(MemoryMarshal.TryGetArray(clipMemory,out ArraySegment<UiClipEntry> clipStorage),"clip backing storage"); Assert.True(MemoryMarshal.TryGetArray(draw.Clips,out ArraySegment<UiClipEntry> clipStorageAgain),"clip backing storage again"); Assert.True(ReferenceEquals(clipStorage.Array,clipStorageAgain.Array),"clips reuse backing array");
        var invalid=XamlLoader.Load("<Canvas Width=\"1\" />"); Assert.True(!invalid.Success&&invalid.Diagnostics.Any(x=>x.Code=="XAML002"),"unknown element diagnostic");
        var shell=XamlLoader.LoadFrame(File.ReadAllText(Path.Combine(AppContext.BaseDirectory,"EditorShell.xaml"))); Assert.True(shell.Success,"EditorShell frame asset"); var shellFrame=shell.Frame!; shellFrame.Layout(new(960,540),1); var shellDraw=shellFrame.ExtractDrawList(new UiFrameContext(new(960,540),1,1)); Assert.Equal(5,shellDraw.Commands.Length,"shell regions at 960x540"); Assert.Equal(new UiRect(0,0,960,48),shell.Frame.Root.Children[0].Bounds,"toolbar geometry"); Assert.Equal(new UiRect(220,48,520,468),shell.Frame.Root.Children[1].Children[1].Bounds,"viewport geometry"); var order=shellDraw.Commands.Span.ToArray().Select(x=>x.Color).ToArray(); shellFrame.Layout(new(800,450),1); var resized=shellFrame.ExtractDrawList(new UiFrameContext(new(800,450),1,2)); Assert.Equal(new UiRect(0,0,800,48),shell.Frame.Root.Children[0].Bounds,"resized toolbar geometry"); Assert.Equal(new UiRect(220,48,360,378),shell.Frame.Root.Children[1].Children[1].Bounds,"resized fill geometry"); Assert.True(order.SequenceEqual(resized.Commands.Span.ToArray().Select(x=>x.Color)),"stable draw order/colors"); foreach(var command in resized.Commands.Span){Assert.True(command.Bounds.X>=0&&command.Bounds.Y>=0&&command.Bounds.X+command.Bounds.Width<=800&&command.Bounds.Y+command.Bounds.Height<=450,"visible bounds inside resized viewport"); Assert.True(command.Clip.X>=0&&command.Clip.Y>=0&&command.Clip.X+command.Clip.Width<=800&&command.Clip.Y+command.Clip.Height<=450,"clip inside resized viewport");}
        Console.WriteLine("DeltaXAML.Core.Tests: passed");
    }
}
